// import pattern_1 from "./Pattern_1";
// import pattern_2 from "./Pattern_2";
// import pattern_3 from "./Pattern_3";
// import pattern_4 from "./Pattern_4";
// import pattern_5 from "./Pattern_5";
// import pattern_6 from "./Pattern_6";
// import pattern_7 from "./Pattern_7";
// import pattern_8 from "./Pattern_8";
// import pattern_9 from "./Pattern_9";
// import pattern_10 from "./Pattern_10";
// import pattern_11 from "./Pattern_11";
// import pattern_12 from "./Pattern_12";
// import pattern_13 from "./Pattern_13";
// import pattern_14 from "./Pattern_14";
// import pattern_15 from "./Pattern_15";
// import pattern_16 from "./Pattern_16";
// import pattern_17 from "./Pattern_17";
// import pattern_18 from "./Pattern_18";
// import pattern_19 from "./Pattern_19";
// import pattern_20 from "./Pattern_20";
import pattern_21 from "./Pattern_21";

// pattern_1();
// pattern_2();
// pattern_3();
// pattern_4();
// pattern_5();
// pattern_6();
// pattern_7();
// pattern_8();
// pattern_9();
// pattern_10();
// pattern_11();
// pattern_12();
// pattern_13();
// pattern_14();
// pattern_15();
// pattern_16();
// pattern_17();
// pattern_18();
// pattern_19();
// pattern_20();
pattern_21();
